name 'security'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures security'
long_description 'Installs/Configures security'
version '0.1.0'
